### PR TITLE
Support SVG with only viewbox specified

### PR DESCRIPTION
**Pull request by borodean**
When both `width` and `height` are not specified, `viewbox` could be a measure for the dimensions of an image.

### CODE REVIEW

**Comment by borodean** [comment]
Looks like Travis failed due to NPM unavailability.

**Comment by ai** [comment]
@netroy what do you think about this issue? I need to fix it too. Maybe I can help?

**Comment by kyleolsondesign** [comment]
Any updates on this?

**Comment by zeke** [comment]
@kyleolsondesign @ai I've emailed npm support to try to claim ownership of this package on npm, so we can get fixes like this rolled in. I'll keep you posted.

**Comment by borodean** [comment]
I'll review the code according to my latest findings I've contributed to https://github.com/lob/calipers/pull/30, check the tests and merge it.

**Comment by borodean** [comment]
Improvements:
- learns to calculate dimensions if only a `viewBox` is specified;
- ignores `width` and `height` set in percents;
- handles single-quoted SVGs.

@zeke, can we release?

**Comment by shinnn** [comment]
https://github.com/image-size/image-size/commit/0d6723b3345ae81d41f2c27e50c89cca522c377d

**Pull request merged**
