### PR TITLE
Add basic support for the DDS file format

### PR DESCRIPTION
**Pull request by stevenvergenz**
DDS isn't supported by browsers, but is pretty common in 3d games. This commit adds support for parsing the DDS header structure for width and height metadata.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks, @stevenvergenz! Can you add a sample DDS file to `spec/images` (ideally valid and invalid versions) so we can get some test coverage around this feature?

See https://github.com/image-size/image-size/tree/master/specs/images/valid

**Comment by stevenvergenz** [comment]
Hmm, I guess that means I need to implement file validation, huh. I just check the magic number and grab a byte offset right now.

**Comment by stevenvergenz** [comment]
I've added a valid file, but I'm not sure where to find an invalid one, or how to tell if the uint32 that I pull from the file is a reasonable image size. Thoughts?

**Comment by zeke** [comment]
What about just adding a fake DDS file?

```
echo "not a real DDS file" > invalid.dds
```

**Comment by stevenvergenz** [comment]
Good point lol, any other file is a malformed DDS file. Added.

**Comment by zeke** [comment]
Hey @shinnn, any idea why Travis is not testing this PR?

**Comment by netroy** [comment]
@stevenvergenz released as #0.5.4 .. replaced your sample image with something I generated, so we don't have top worry about the license for the image

**Pull request closed without merging**
