### PR TITLE
Add Hosted API link to readme

### PR DESCRIPTION
**Pull request by chrisvxd**
This PR adds a link to the [saasified version](https://image-size.saasify.sh) of image-size to the readme.

### Example

```sh
curl -X POST 'https://api.saasify.sh/1/call/dev/image-size/sizebyurl' \
  -H 'content-type: application/json' \
  -d '{
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/23/Close_up_of_a_black_domestic_cat.jpg"
  }'
```

Which returns the dimension of the image

```json
{
  "height": 4032,
  "orientation": 1,
  "width": 3024,
  "type": "jpg"
}
```

### Context
[Saasify](http://saasify.sh) is a bootstrapped startup that I cofounded **to provide sustainable funding for open source developers**.

We're making it really simple to transform OSS projects like image-size into FaaS (Function-as-a-Service) APIs that scale funding as usage increases.

You can see the source code we used to generate the saasified version [here](https://github.com/saasify-sh/image-size).

### Notes
* We haven't promoted this API publicly yet and won't do so without your approval.
* **The majority of all revenue generated by this API is set aside for image-size maintainers**. We do this automatically even if you haven't setup payout info. Payout details can be customized via [Stripe Connect](https://stripe.com/connect).
* We're happy to add you as an owner to any resources so you can customize anything you'd like.
* Things like pricing, rate limits, docs, domain, and website theming are all configurable.
* Saasify takes care of all support requests, so you can focus on OSS.
* You can read more about our [mission](https://saasify.sh/#/mission) on our [site](https://saasify.sh).

### Next Steps
* It's totally okay if you don't want to accept this PR or offer a saasfied version of image-size. Our platform is really young and feedback is the most important thing we need right now.
* We're happy to answer any questions you may have in this thread. Also feel free to get in touch via [email](mailto:dev@saasify.sh) or on our [open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY).

Thanks for all the amazing work you've put into image-size && we're looking forward to helping you earn passive income from this work!

### CODE REVIEW

**Comment by netroy** [comment]
@chrisvxd Thanks a lot for choosing this module as one of your examples. 
Also, saasify looks like a wonderful Idea. I genuinely feel honoured.

Right now, I can't think through clearly enough, to decide if I want this linked in the Readme or not.
It's most likely an non-issue. But, let me get back to you in a week or so with a clearer mind.

PS: I have no objection on saasify offering a hosted version of image-size.
So, please feel free to add it to your showcase. 
And, if that brings you any significant revenue, I hope you can use it to invest in saasify & other OSS projects.

**Comment by chrisvxd** [comment]
@netroy thanks for such a positive response. Please feel free to take all the time you need, it's no rush.

Mind if I ask what your hesitation is caused by?

**Comment by netroy** [comment]
> Mind if I ask what your hesitation is caused by?
Nothing in particular from this PR.

**Comment by chrisvxd** [comment]
Awesome, thanks for merging @netroy!

It would be great to get you in our [open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY) so we can stay in touch.

**Pull request merged**
