### PR TITLE
Duplicated XMP 

### PR DESCRIPTION
**Pull request by Aldor007**
Hi
Some of the jpg that I use have 2 times XMP in itself. This PR makes possible to read their resolution correctly.
Thanks for feedback

### CODE REVIEW

**Comment by LinusU** [comment]
Do you have a test case that we could look at?

**Comment by Aldor007** [comment]
Example image: http://ocdn.eu/images/test/Yzk7MDA_/bdd16ce0c8175832af2be68554cf5a7f.jpg
image-size without changes give:
````
[TypeError: Invalid JPG, marker table corrupted]
```

**Comment by shinnn** [comment]
image-size seems to work fine for me. I think what really should be fixed is the image file, not this library.

**Comment by Aldor007** [comment]
I really would like to fix image but I can't. My colleague found better solution so I'm closing this PR.

**Comment by shinnn** [comment]
>  My colleague found better solution

@Aldor007 Just out of curiosity, can you tell us *the better solution*?

**Comment by Ndrou** [comment]
@Aldor007 What is your solution ? I have the same problem.

**Comment by kuebk** [comment]
We did it that way: https://gist.github.com/kuebk/d0c4c12ea03fb37ce0107f1781d10142

If you are interested with above changes let me know, I can prepare PR.

**Pull request closed without merging**
