### PR TITLE
Use tsup for ESM/CJS builds

### PR DESCRIPTION
**Pull request by shmuli9**
- Use tsup to build
- Migrated to vitest (for the seamless esm support)
- Update README with ESM examples
---------
- [x] yarn build
- [x] yarn lint
- [x] yarn generate-docs
- [x] yarn test

**Please can a reviewer make sure the produced artifact actually works as I am unsure how to test without publishing to npm**

### arethetypeswrong
Used `npx --yes @arethetypeswrong/cli --pack .` to ensure exports are correct for ESM/CJS consumption

image

### CODE REVIEW

**Comment by netroy** [comment]
Thanks for the help, but this PR does quite a lot of changes that I don't want to merge.
for example, instead of migrating to vite, I've gone the other direction and removed mocha+chai+sinon, and now only use nodejs native testing utils.

I've setup tsup from scratch, and added you as [co-author](https://github.com/image-size/image-size/pull/370/commits/97a20c44b12ef0410003453bf69717ef61cc2106) on the 2.0 PR.
I'm going to close this PR.

Sorry that you put so much effort, and I'm closing this. But thanks for helping push this forward 🙇🏽

**Comment by shmuli9** [comment]
Happy to help, and glad if it helps v2 cross the line

May I ask why you've gone with native node testing?

From what I can tell the pro is it's native, not outside dep

But cons are you have to maintain 2 tsconfig files, and the command is quite complicated too because of nodes non-native TS support

**Comment by netroy** [comment]
> May I ask why you've gone with native node testing?

As I get older, I grow more tired of large dependency trees.
This npm package and this repo are also an avenue for me to take a break from the mess that dependency management has become.
 
If ESM migration wasn't such a mess, I'd probably not even have used tsup. 
Smaller lockfiles bring me peace.

**Comment by shmuli9** [comment]
Fair enough

Thanks for all your work maintaining this repo.

I was shocked to find almost no other library that was usable on a cloudflare worker because all the other image libs have loads of compute heavy features which seem to leverage node native features a lot

This is really helpful!

**Pull request closed without merging**
