### PR TITLE
Update dependencies. support only node 14, 16, and 18

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Comment by eexit** [comment]
Hello, 

This change is breaking and should have been tagged accordingly! I'm using your lib in a project of mine and while I'm trying to upgrade an old stack, the latest version of your lib gets picked by yarn and is incompatible with Node 12.

I would be nice if you could tag this BC as 2.0.0 and not 1.0.2.

https://semver.org/

Thanks!

**Comment by netroy** [comment]
@eexit I'm fairly familiar with semantic versioning. From the link you shared:
> MAJOR version when you make incompatible API changes 

and, There are no actual code or API changes in here to justify bumping a major version.

Node 12 active support ended over 2 years ago, and it went EOL 7 months ago. I think it'd be unfair to expect anyone doing this for free to keep maintaining support for node 12, 10, or earlier versions.

That said, I understand if upgrading to node 16 breaks stuff. so, if you are using this library directly, I'd recommend fixing the version to `1.0.1` without any `^` or `~`. 
But, if this library is getting pulled in as a transitive dependency, you could use yarn resolutions to fix the version instead.

**Comment by netroy** [comment]
@eexit [your repo says that you dropped support for node 12 as well](https://github.com/eexit/ghost-storage-cloudinary/commit/8e0cada331ab24c5b46918cecb032f1eff0fae1f).
That's confusing.

**Comment by eexit** [comment]
Hello,

> MAJOR version when you make incompatible API changes

Dropping a support for a software version should be considered like a MAJOR change, and I know I messed-up in my versioning as well.

> Node 12 active support ended over 2 years ago, and it went EOL 7 months ago. I think it'd be unfair to expect anyone doing this for free to keep maintaining support for node 12, 10, or earlier versions.

I know, and I can't blame you for this. Don't get me wrong here.

I was upgrading an old version of Ghost which was still running on node 12 and when I installed my project, pulling 1.0.2 was of course not compatible anymore with node 12. This gave me extra miles to complete my migration because of a bad versioning.

My migration is completed now, so don't worry, but I thought it would be nice to let you know about this for the future.

Thanks anyway for your lib ✌🏻

**Pull request merged**
